# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20170316_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='emp_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
