# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myems', '0002_auto_20170317_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(related_name='departments', through='myems.DeptEmp', to='myems.Department'),
        ),
    ]
