# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 19:28
from __future__ import unicode_literals

from django.db import migrations
import myems.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('myems', '0004_auto_20170317_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=stdimage.models.StdImageField(blank=True, max_length=255, null=True, storage=myems.models.LocalFileSystemStorage(), upload_to=myems.models.upload_path_handler),
        ),
    ]
